# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ebugs_message/Command.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ebugs_message.msg

class Command(genpy.Message):
  _md5sum = "4f354046c8f89b31b50f4af3a1191dee"
  _type = "ebugs_message/Command"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Position[] robots_position
Position target_position
================================================================================
MSG: ebugs_message/Position
int16 x
int16 y
int16 angle"""
  __slots__ = ['robots_position','target_position']
  _slot_types = ['ebugs_message/Position[]','ebugs_message/Position']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       robots_position,target_position

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Command, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.robots_position is None:
        self.robots_position = []
      if self.target_position is None:
        self.target_position = ebugs_message.msg.Position()
    else:
      self.robots_position = []
      self.target_position = ebugs_message.msg.Position()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.robots_position)
      buff.write(_struct_I.pack(length))
      for val1 in self.robots_position:
        _x = val1
        buff.write(_get_struct_3h().pack(_x.x, _x.y, _x.angle))
      _x = self
      buff.write(_get_struct_3h().pack(_x.target_position.x, _x.target_position.y, _x.target_position.angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.robots_position is None:
        self.robots_position = None
      if self.target_position is None:
        self.target_position = ebugs_message.msg.Position()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.robots_position = []
      for i in range(0, length):
        val1 = ebugs_message.msg.Position()
        _x = val1
        start = end
        end += 6
        (_x.x, _x.y, _x.angle,) = _get_struct_3h().unpack(str[start:end])
        self.robots_position.append(val1)
      _x = self
      start = end
      end += 6
      (_x.target_position.x, _x.target_position.y, _x.target_position.angle,) = _get_struct_3h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.robots_position)
      buff.write(_struct_I.pack(length))
      for val1 in self.robots_position:
        _x = val1
        buff.write(_get_struct_3h().pack(_x.x, _x.y, _x.angle))
      _x = self
      buff.write(_get_struct_3h().pack(_x.target_position.x, _x.target_position.y, _x.target_position.angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.robots_position is None:
        self.robots_position = None
      if self.target_position is None:
        self.target_position = ebugs_message.msg.Position()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.robots_position = []
      for i in range(0, length):
        val1 = ebugs_message.msg.Position()
        _x = val1
        start = end
        end += 6
        (_x.x, _x.y, _x.angle,) = _get_struct_3h().unpack(str[start:end])
        self.robots_position.append(val1)
      _x = self
      start = end
      end += 6
      (_x.target_position.x, _x.target_position.y, _x.target_position.angle,) = _get_struct_3h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3h = None
def _get_struct_3h():
    global _struct_3h
    if _struct_3h is None:
        _struct_3h = struct.Struct("<3h")
    return _struct_3h
