// Generated by gencpp from file ebugs_message/Force.msg
// DO NOT EDIT!


#ifndef EBUGS_MESSAGE_MESSAGE_FORCE_H
#define EBUGS_MESSAGE_MESSAGE_FORCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ebugs_message
{
template <class ContainerAllocator>
struct Force_
{
  typedef Force_<ContainerAllocator> Type;

  Force_()
    : Fx(0)
    , Fy(0)  {
    }
  Force_(const ContainerAllocator& _alloc)
    : Fx(0)
    , Fy(0)  {
  (void)_alloc;
    }



   typedef int16_t _Fx_type;
  _Fx_type Fx;

   typedef int16_t _Fy_type;
  _Fy_type Fy;




  typedef boost::shared_ptr< ::ebugs_message::Force_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ebugs_message::Force_<ContainerAllocator> const> ConstPtr;

}; // struct Force_

typedef ::ebugs_message::Force_<std::allocator<void> > Force;

typedef boost::shared_ptr< ::ebugs_message::Force > ForcePtr;
typedef boost::shared_ptr< ::ebugs_message::Force const> ForceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ebugs_message::Force_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ebugs_message::Force_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ebugs_message

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ebugs_message': ['/home/alexandre/ebugs_ws/src/ebugs_message/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ebugs_message::Force_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ebugs_message::Force_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ebugs_message::Force_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ebugs_message::Force_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ebugs_message::Force_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ebugs_message::Force_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ebugs_message::Force_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71daa568e162227b07dbde011fd0127a";
  }

  static const char* value(const ::ebugs_message::Force_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71daa568e162227bULL;
  static const uint64_t static_value2 = 0x07dbde011fd0127aULL;
};

template<class ContainerAllocator>
struct DataType< ::ebugs_message::Force_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ebugs_message/Force";
  }

  static const char* value(const ::ebugs_message::Force_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ebugs_message::Force_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 Fx\n\
int16 Fy\n\
";
  }

  static const char* value(const ::ebugs_message::Force_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ebugs_message::Force_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Fx);
      stream.next(m.Fy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Force_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ebugs_message::Force_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ebugs_message::Force_<ContainerAllocator>& v)
  {
    s << indent << "Fx: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Fx);
    s << indent << "Fy: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Fy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EBUGS_MESSAGE_MESSAGE_FORCE_H
