// Generated by gencpp from file ebugs_message/Position.msg
// DO NOT EDIT!


#ifndef EBUGS_MESSAGE_MESSAGE_POSITION_H
#define EBUGS_MESSAGE_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ebugs_message
{
template <class ContainerAllocator>
struct Position_
{
  typedef Position_<ContainerAllocator> Type;

  Position_()
    : x(0)
    , y(0)
    , angle(0)  {
    }
  Position_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , angle(0)  {
  (void)_alloc;
    }



   typedef int16_t _x_type;
  _x_type x;

   typedef int16_t _y_type;
  _y_type y;

   typedef int16_t _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::ebugs_message::Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ebugs_message::Position_<ContainerAllocator> const> ConstPtr;

}; // struct Position_

typedef ::ebugs_message::Position_<std::allocator<void> > Position;

typedef boost::shared_ptr< ::ebugs_message::Position > PositionPtr;
typedef boost::shared_ptr< ::ebugs_message::Position const> PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ebugs_message::Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ebugs_message::Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ebugs_message

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ebugs_message': ['/home/alexandre/ebugs_ws/src/ebugs_message/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ebugs_message::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ebugs_message::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ebugs_message::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ebugs_message::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ebugs_message::Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ebugs_message::Position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ebugs_message::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f2c3eb36e55b382477373818947f398";
  }

  static const char* value(const ::ebugs_message::Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f2c3eb36e55b382ULL;
  static const uint64_t static_value2 = 0x477373818947f398ULL;
};

template<class ContainerAllocator>
struct DataType< ::ebugs_message::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ebugs_message/Position";
  }

  static const char* value(const ::ebugs_message::Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ebugs_message::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 x\n\
int16 y\n\
int16 angle\n\
";
  }

  static const char* value(const ::ebugs_message::Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ebugs_message::Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ebugs_message::Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ebugs_message::Position_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
    s << indent << "angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EBUGS_MESSAGE_MESSAGE_POSITION_H
